/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BorrowBookController;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import model.Book;
import model.Reader;

/**
 *
 * @author alychinque
 */
public class BorrowBook extends javax.swing.JFrame {

    private final BorrowBookController controller;
    private final ArrayList<Reader> readers;
    private final ArrayList<Book> library;
    private String[] books;
    private String[] readerName;

    /**
     * Creates new form RentBook
     */
//    public BorrowBook() {
//        initComponents();
//        this.controller = new BorrowBookController(this);
//    }
    public BorrowBook(ArrayList<Reader> readers, ArrayList<Book> library) {
        initComponents();
        this.controller = new BorrowBookController(this);
        this.readers = readers;
        this.library = library;
        setBookjComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReturnBook1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBooks = new javax.swing.JComboBox<>();
        jComboBoxReaders = new javax.swing.JComboBox<>();
        jButtonBorrowBook = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jButtonReturnBook1.setBackground(new java.awt.Color(255, 255, 0));
        jButtonReturnBook1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonReturnBook1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReturnBook1.setText("Borrow Book");
        jButtonReturnBook1.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonReturnBook1.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonReturnBook1.setPreferredSize(new java.awt.Dimension(160, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/blackBooks.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Reader:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Book:");

        jComboBoxBooks.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxBooks.setMaximumSize(new java.awt.Dimension(470, 30));
        jComboBoxBooks.setMinimumSize(new java.awt.Dimension(470, 30));
        jComboBoxBooks.setPreferredSize(new java.awt.Dimension(470, 30));

        jComboBoxReaders.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxReaders.setMaximumSize(new java.awt.Dimension(470, 30));
        jComboBoxReaders.setMinimumSize(new java.awt.Dimension(470, 30));
        jComboBoxReaders.setPreferredSize(new java.awt.Dimension(470, 30));

        jButtonBorrowBook.setBackground(new java.awt.Color(255, 255, 0));
        jButtonBorrowBook.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonBorrowBook.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrowBook.setText("Borrow Book");
        jButtonBorrowBook.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonBorrowBook.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonBorrowBook.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonBorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrowBookActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxReaders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxBooks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxReaders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jButtonBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.back();

    }//GEN-LAST:event_backActionPerformed

    private void jButtonBorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrowBookActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Reader: " + jComboBoxReaders.getSelectedItem()
                +"\nBook: " + jComboBoxBooks.getSelectedItem()
                +"\nAre you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // yes option
            controller.borrowBook( jComboBoxReaders.getSelectedItem() , jComboBoxBooks.getSelectedItem() );
        } else {
            // no option
        }
    }//GEN-LAST:event_jButtonBorrowBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setBookjComboBox() {
        convertArray(library, readers);
        jComboBoxBooks.setModel(new javax.swing.DefaultComboBoxModel<>(books));
        jComboBoxReaders.setModel(new javax.swing.DefaultComboBoxModel<>(readerName));
        
        jComboBoxBooks.addActionListener(controller);
        jComboBoxBooks.setActionCommand("book");
        
        jComboBoxReaders.addActionListener(controller);
        jComboBoxReaders.setActionCommand("reader");
    }

    private void convertArray(ArrayList<Book> booksLibrary, ArrayList<Reader> readers) {
        books = new String[booksLibrary.size()];
        for (int i = 0; i < booksLibrary.size(); i++) {
            books[i] = booksLibrary.get(i).getBookTitle();
        }
        readerName = new String[readers.size()];
        for (int i = 0; i < readers.size(); i++) {
            readerName[i] = readers.get(i).getReaderName() + " " + readers.get(i).getReaderSurname();
        }
        Arrays.sort(books);
        Arrays.sort(readerName);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButtonBorrowBook;
    private javax.swing.JButton jButtonReturnBook1;
    private javax.swing.JComboBox<String> jComboBoxBooks;
    private javax.swing.JComboBox<String> jComboBoxReaders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
