/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ListBooksController;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Book;

/**
 *
 * @author alychinque
 */
public class ListBooks extends javax.swing.JFrame {
    
    private final ListBooksController controller;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel[] panelBook;
    private javax.swing.JLabel[] title;
    private javax.swing.JLabel[] nameAuthor;
    private javax.swing.JLabel[] surnameAuthor;
    private javax.swing.JLabel[] genre;
    private javax.swing.JButton[] btnRent;
    Object rowInfoData[] = new Object[4];

    

    /**
     * Creates new form ListBooks
     */
    public ListBooks(ArrayList<Book> library, int sizeLibrary) {
        initComponents();
        this.controller = new ListBooksController(this);
        setTable(library);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setRequestFocusEnabled(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/blackBooks.png"))); // NOI18N

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Author's name", "Author's surname", "Genre"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(logo)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.back();
    }//GEN-LAST:event_backActionPerformed

//    private void genVariables(ArrayList<Book> library, int sizeArray) {
//        try {
//            System.out.println("enter into try");
//            panelBook = new JPanel[sizeArray];
//            title = new JLabel[sizeArray];
//            nameAuthor = new JLabel[sizeArray];
//            surnameAuthor = new JLabel[sizeArray];
//            genre = new JLabel[sizeArray];
//            panel = new JPanel();
//            int sizeYaxisPanel = sizeArray * 30;
//            System.out.println(sizeYaxisPanel);
//            panel.setPreferredSize(new java.awt.Dimension(650, sizeYaxisPanel));
//            panel.setLayout(null);
//            
//            int yAxis = 0;
//            for (int i = 0; i < sizeArray; i++) {
//                panelBook[i] = new JPanel();
//                title[i] = new JLabel();
//                nameAuthor[i] = new JLabel();
//                surnameAuthor[i] = new JLabel();
//                genre[i] = new JLabel();
//                btnRent = new JButton[sizeArray];
//                System.out.println("created "+ i + "panels and labels");
//                // panel
//                panelBook[i].setBounds(0, 0, 650, yAxis);
//                // title
//                title[i].setFont(new java.awt.Font("Liberation Mono", 0, 11)); // NOI18N
//                title[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
//                title[i].setText(library.get(i).getBookTitle());
//                title[i].setPreferredSize(new java.awt.Dimension(150, 30));
//                title[i].setBounds(0, 0, 150, 30);String[] columns = {"Title", "Author's Name", "Author's Surname", "Genr
//                // name author
//                nameAuthor[i].setFont(new java.awt.Font("Liberation Mono", 0, 11)); // NOI18N
//                nameAuthor[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
//                nameAuthor[i].setText(library.get(i).getAuthorFirstName());
//                nameAuthor[i].setPreferredSize(new java.awt.Dimension(150, 30));
//                nameAuthor[i].setBounds(150, 0, 150, 30);
//                // surname author
//                surnameAuthor[i].setFont(new java.awt.Font("Liberation Mono", 0, 11)); // NOI18N
//                surnameAuthor[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
//                surnameAuthor[i].setText(library.get(i).getAuthorLastName());
//                surnameAuthor[i].setPreferredSize(new java.awt.Dimension(150, 30));
//                surnameAuthor[i].setBounds(300, 0, 150, 30);
//                // genre
//                genre[i].setFont(new java.awt.Font("Liberation Mono", 0, 11)); // NOI18N
//                genre[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
//                genre[i].setText(library.get(i).getGenre());
//                genre[i].setPreferredSize(new java.awt.Dimension(150, 30));
//                genre[i].setBounds(450, 0, 150, 30);
//                // rent 50x35
//                System.out.println("chega aqui?");
////                btnRent[i].addActionListener(controller);
////                btnRent[i].setActionCommand(library.get(i).getIdBook());
////                btnRent[i].setBounds(600, 0, 50, 30);
//                // add to panel
//                panelBook[i].add(title[i]);
//                panelBook[i].add(nameAuthor[i]);
//                panelBook[i].add(surnameAuthor[i]);
//                panelBook[i].add(genre[i]);
//                panelBook[i].add(btnRent[i]);
//                // add panel to the external panel
//                panel.add(panelBook[i]);
//                System.out.println("final for");
//                yAxis += 30;
//            }
//            jScrollPane1.setViewportView(panel);
//            this.validate();
//            this.repaint();
//        } catch (Exception e) {
//            
//        }
//    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

    private void genVariables2(ArrayList<Book> library) {
        
    }

    private void setTable(ArrayList<Book> library) {
        DefaultTableModel infoTableModel = (DefaultTableModel) jTable.getModel();
        infoTableModel.setRowCount(0);
        
        for(int i=1; i< library.size(); i++){
            rowInfoData[0] = library.get(i).getBookTitle();
            rowInfoData[1] = library.get(i).getAuthorFirstName();
            rowInfoData[2] = library.get(i).getAuthorLastName();
            rowInfoData[3] = library.get(i).getGenre();
            
            infoTableModel.addRow(rowInfoData);
        }
        System.out.println(infoTableModel.getRowCount());
        
    }
}
