                                        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ReadersController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Reader;

/**
 *
 * @author alychinque
 */
public class Readers extends javax.swing.JFrame {

    private final ReadersController controller;
    private static ArrayList<Reader> readers = new ArrayList<>();
    
    /**
     * Creates new form Reader
     */
    public Readers() {
        initComponents();
        this.controller = new ReadersController(this);
    }

    public Readers(ArrayList<Reader> readers) {
        initComponents();
        this.controller = new ReadersController(this);
        this.readers = readers;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButtonAddReader = new javax.swing.JButton();
        jButtonListReader = new javax.swing.JButton();
        jButtonName = new javax.swing.JButton();
        nameReader = new javax.swing.JTextField();
        jLabelNameReader = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/blackBooks.png"))); // NOI18N

        jButtonAddReader.setBackground(new java.awt.Color(51, 102, 255));
        jButtonAddReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonAddReader.setText("Add Reader");
        jButtonAddReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddReaderActionPerformed(evt);
            }
        });

        jButtonListReader.setBackground(new java.awt.Color(255, 255, 0));
        jButtonListReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonListReader.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListReader.setText("List Readers / Edit / Delete");
        jButtonListReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonListReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonListReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonListReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListReaderActionPerformed(evt);
            }
        });

        jButtonName.setBackground(new java.awt.Color(255, 153, 51));
        jButtonName.setForeground(new java.awt.Color(0, 0, 0));
        jButtonName.setText("Search");

        jLabelNameReader.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNameReader.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNameReader.setText("Name Reader");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNameReader)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameReader, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButtonAddReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonListReader, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabelNameReader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameReader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonName))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.back();
    }//GEN-LAST:event_backActionPerformed

    private void jButtonListReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListReaderActionPerformed
        if(readers.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Readers Added");
        }else{
            controller.goListReaders(this.readers);
        }
    }//GEN-LAST:event_jButtonListReaderActionPerformed

    private void jButtonAddReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReaderActionPerformed
        controller.goAddReader();
    }//GEN-LAST:event_jButtonAddReaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButtonAddReader;
    private javax.swing.JButton jButtonListReader;
    private javax.swing.JButton jButtonName;
    private javax.swing.JLabel jLabelNameReader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nameReader;
    // End of variables declaration//GEN-END:variables
}