                                        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ReadersController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Reader;

/**
 *
 * @author alychinque
 */
public class Readers extends javax.swing.JFrame {

    private final ReadersController controller;
    private ArrayList<Reader> readers = new ArrayList<>();
    
    /**
     * Creates new form Reader
     */
    public Readers() {
        initComponents();
        this.controller = new ReadersController(this);
    }

    public Readers(ArrayList<Reader> readers) {
        initComponents();
        this.controller = new ReadersController(this);
        this.readers = readers;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButtonAddReader = new javax.swing.JButton();
        jButtonEditReader = new javax.swing.JButton();
        jButtonDeleteReader = new javax.swing.JButton();
        jButtonListReader = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldIdReader = new javax.swing.JTextField();
        jTextFieldNameReader = new javax.swing.JTextField();
        jLabelidReader = new javax.swing.JLabel();
        jLabelNameReader = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/blackBooks.png"))); // NOI18N

        jButtonAddReader.setBackground(new java.awt.Color(51, 102, 255));
        jButtonAddReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonAddReader.setText("Add Reader");
        jButtonAddReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonAddReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddReaderActionPerformed(evt);
            }
        });

        jButtonEditReader.setBackground(new java.awt.Color(0, 204, 0));
        jButtonEditReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonEditReader.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditReader.setText("Edit Reader");
        jButtonEditReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonEditReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonEditReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonEditReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditReaderActionPerformed(evt);
            }
        });

        jButtonDeleteReader.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDeleteReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonDeleteReader.setText("Del Reader");
        jButtonDeleteReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonDeleteReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonDeleteReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonDeleteReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteReaderActionPerformed(evt);
            }
        });

        jButtonListReader.setBackground(new java.awt.Color(255, 255, 0));
        jButtonListReader.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonListReader.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListReader.setText("List Readers");
        jButtonListReader.setMaximumSize(new java.awt.Dimension(160, 50));
        jButtonListReader.setMinimumSize(new java.awt.Dimension(160, 50));
        jButtonListReader.setPreferredSize(new java.awt.Dimension(160, 50));
        jButtonListReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListReaderActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Search");

        jLabelidReader.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelidReader.setForeground(new java.awt.Color(204, 204, 204));
        jLabelidReader.setText("ID Reader");

        jLabelNameReader.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNameReader.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNameReader.setText("Name Reader");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelidReader)
                    .addComponent(jTextFieldIdReader, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameReader)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNameReader, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonAddReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonEditReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonDeleteReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButtonListReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(back)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelidReader)
                    .addComponent(jLabelNameReader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdReader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameReader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButtonListReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditReaderActionPerformed
    }//GEN-LAST:event_jButtonEditReaderActionPerformed

    private void jButtonAddReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReaderActionPerformed
        controller.goAddReader();
    }//GEN-LAST:event_jButtonAddReaderActionPerformed

    private void jButtonDeleteReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteReaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteReaderActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.back();
    }//GEN-LAST:event_backActionPerformed

    private void jButtonListReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListReaderActionPerformed
        if(readers.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Readers Added");
        }else{
            controller.goListReaders(readers);
        }
    }//GEN-LAST:event_jButtonListReaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddReader;
    private javax.swing.JButton jButtonDeleteReader;
    private javax.swing.JButton jButtonEditReader;
    private javax.swing.JButton jButtonListReader;
    private javax.swing.JLabel jLabelNameReader;
    private javax.swing.JLabel jLabelidReader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdReader;
    private javax.swing.JTextField jTextFieldNameReader;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}